<?php

class DivideByZeroException extends Exception
{
    public function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub
        return "Can't divide by zero";
    }

}
